[package]
name = "trafw-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
pnet = { version = "0.35.0", features = ["pcap", "pnet_datalink"] }
chrono = "0.4"
crossbeam = "0.8"
lazy_static = "1.4"
pcap = "2.2.0"
